version: 0.2

phases:
  pre_build:
    commands:
      - CACHE_DIR='docker-img-cache'
      - CACHED_FILE='docker-img-cache/cache/test.md'
  build:
    commands:
      - ls $CACHE_DIR/cache || true
      - ls -sh $CACHED_FILE || true
      # If file exist, print its content and size
      - if [ -f $CACHED_FILE ]; then echo "File is in cache"; ls -sh $CACHED_FILE; cat $CACHED_FILE ; fi
      # Else create file, print its size
      - if ! [ -f $CACHED_FILE ]; then echo "Hello cache world" > $CACHED_FILE; echo "File created"; ls -sh $CACHED_FILE; fi
      - ls $CACHE_DIR/cache
cache:
  paths:
    - 'docker-img-cache/**/*'
