version: 0.2

env:
  variables:
    IMAGE_CACHE_ROOT: /root/.docker-cache

phases:
  pre_build:
    commands:
      - CACHED_FILE=$IMAGE_CACHE_ROOT/test.md
  build:
    commands:
      - ls $IMAGE_CACHE_ROOT || true
      - ls -sh $CACHED_FILE || true
      # If file exist, print its content and size
      - if [ -f $CACHED_FILE ]; then echo "File is in cache"; ls -sh $CACHED_FILE; cat $CACHED_FILE ; fi
      # Else create file, print its size
      - if ! [ -f $CACHED_FILE ]; then echo "Hello cache world" > $CACHED_FILE; echo "File created"; ls -sh $CACHED_FILE; fi
      - ls $IMAGE_CACHE_ROOT
cache:
  paths:
    - /root/**
